package ru.hse.app.androidApp.ui.theme

import androidx.compose.ui.graphics.Color

//generated by https://materialkolor.com
//Color palette was taken here: https://coolors.co/palette/e63946-f1faee-a8dadc-457b9d-1d3557

internal val Seed = Color(0xFF1D3557)

// Светлая тема
internal val BackgroundLight = Color(0xFFEBEBEB) // Светло-серый
internal val OnBackgroundLight = Color(0xFF000000) // Черный
internal val PrimaryLight = Color(0xFF013648) // Синий
internal val OnPrimaryLight = Color(0xFFFFFFFF) // Белый
internal val OnPrimaryContainerLight = Color(0xFFFFFFFF) // Белый
internal val SecondaryLight = Color(0xFFCFEDFF) // Голубой
internal val OnSecondaryLight = Color(0xFF000000) // Черный
internal val TertiaryLight = Color(0xFFF3D0B2) // Бежевый
internal val OnTertiaryLight = Color(0xFF000000) // Черный
internal val ErrorLight = Color(0xFFFF383C) // Ярко-красный
internal val OnErrorLight = Color(0xFFFFA4A4) // Бледно-красный
internal val SurfaceVariantLight = Color(0xFF2A9A47) // Ярко-зеленый
internal val OnSurfaceVariantLight = Color(0xFFB9FFA4) // Бледно-зеленый
internal val SurfaceLight = Color(0xFFD0D7DD) // Средне-серый
internal val OutlineLight = Color(0xFF6D6F6E) // Темно-серый
internal val ScrimLight = Color(0xFFFFFFFF) //Белый

// Темная тема

internal val BackgroundDark = Color(0xFF121212) // Почти черный фон
internal val OnBackgroundDark = Color(0xFFFFFFFF)
internal val PrimaryDark = Color(0xFF4FA3BF) // Осветлённый синий из PrimaryLight
internal val OnPrimaryDark = Color(0xFF001F2A) // Очень тёмный сине-черный
internal val OnPrimaryContainerDark = Color(0xCB125F86) // Очень тёмный сине-черный

internal val SecondaryDark = Color(0xFF6FA4D6) // Более насыщенный голубой
internal val OnSecondaryDark = Color(0xFFFFFFFF)

internal val TertiaryDark = Color(0xFFE0B894) // Тёплый бежевый, мягкий
internal val OnTertiaryDark = Color(0xFF2B1B10)

internal val ErrorDark = Color(0xFFFF6B6E) // Мягче, чем ярко-красный
internal val OnErrorDark = Color(0xFF3A0002)

internal val SurfaceVariantDark = Color(0xFF3FBF63) // Зелёный остаётся живым
internal val OnSurfaceVariantDark = Color(0xFF0F2A16)

internal val SurfaceDark = Color(0xFF1E1E1E) // Карточки, bottom bar, поля
internal val OutlineDark = Color(0xFF8A8A8A) // Контуры, бордеры, divider
internal val ScrimDark = Color(0xFFFFFFFF) //Белый


//internal val PrimaryLight = Color(0xFF485F84)
//internal val OnPrimaryLight = Color(0xFFFFFFFF)
//internal val PrimaryContainerLight = Color(0xFFD5E3FF)
//internal val OnPrimaryContainerLight = Color(0xFF30476A)
////internal val SecondaryLight = Color(0xFF2B6485)
////internal val OnSecondaryLight = Color(0xFFFFFFFF)
//internal val SecondaryContainerLight = Color(0xFFC7E7FF)
//internal val OnSecondaryContainerLight = Color(0xFF064C6B)
////internal val TertiaryLight = Color(0xFF356668)
////internal val OnTertiaryLight = Color(0xFFFFFFFF)
//internal val TertiaryContainerLight = Color(0xFFB9ECEE)
//internal val OnTertiaryContainerLight = Color(0xFF1A4E50)
////internal val ErrorLight = Color(0xFFBB152C)
////internal val OnErrorLight = Color(0xFFFFFFFF)
//internal val ErrorContainerLight = Color(0xFFFFDAD8)
//internal val OnErrorContainerLight = Color(0xFF410007)
////internal val BackgroundLight = Color(0xFFF9F9F9)
//internal val OnBackgroundLight = Color(0xFF1A1C1C)
////internal val SurfaceLight = Color(0xFFF9F9F9)
//internal val OnSurfaceLight = Color(0xFF1A1C1C)
////internal val SurfaceVariantLight = Color(0xFFDCE5D9)
////internal val OnSurfaceVariantLight = Color(0xFF404941)
////internal val OutlineLight = Color(0xFF717970)
//internal val OutlineVariantLight = Color(0xFFC0C9BE)
//internal val ScrimLight = Color(0xFF000000)
//internal val InverseSurfaceLight = Color(0xFF2F3131)
//internal val InverseOnSurfaceLight = Color(0xFFF0F1F1)
//internal val InversePrimaryLight = Color(0xFFB0C7F1)
//internal val SurfaceDimLight = Color(0xFFDADADA)
//internal val SurfaceBrightLight = Color(0xFFF9F9F9)
//internal val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
//internal val SurfaceContainerLowLight = Color(0xFFF3F3F4)
//internal val SurfaceContainerLight = Color(0xFFEEEEEE)
//internal val SurfaceContainerHighLight = Color(0xFFE8E8E8)
//internal val SurfaceContainerHighestLight = Color(0xFFE2E2E2)
//
////internal val PrimaryDark = Color(0xFFB0C7F1)
////internal val OnPrimaryDark = Color(0xFF183153)
//internal val PrimaryContainerDark = Color(0xFF30476A)
//internal val OnPrimaryContainerDark = Color(0xFFD5E3FF)
////internal val SecondaryDark = Color(0xFF98CDF2)
////internal val OnSecondaryDark = Color(0xFF00344C)
//internal val SecondaryContainerDark = Color(0xFF064C6B)
//internal val OnSecondaryContainerDark = Color(0xFFC7E7FF)
////internal val TertiaryDark = Color(0xFF9ECFD1)
////internal val OnTertiaryDark = Color(0xFF003739)
//internal val TertiaryContainerDark = Color(0xFF1A4E50)
//internal val OnTertiaryContainerDark = Color(0xFFB9ECEE)
////internal val ErrorDark = Color(0xFFFFB3B1)
////internal val OnErrorDark = Color(0xFF680011)
//internal val ErrorContainerDark = Color(0xFF92001C)
//internal val OnErrorContainerDark = Color(0xFFFFDAD8)
////internal val BackgroundDark = Color(0xFF121414)
//internal val OnBackgroundDark = Color(0xFFE2E2E2)
////internal val SurfaceDark = Color(0xFF121414)
//internal val OnSurfaceDark = Color(0xFFE2E2E2)
//internal val SurfaceVariantDark = Color(0xFF404941)
//internal val OnSurfaceVariantDark = Color(0xFFC0C9BE)
//internal val OutlineDark = Color(0xFF8A9389)
//internal val OutlineVariantDark = Color(0xFF404941)
//internal val ScrimDark = Color(0xFF000000)
//internal val InverseSurfaceDark = Color(0xFFE2E2E2)
//internal val InverseOnSurfaceDark = Color(0xFF2F3131)
//internal val InversePrimaryDark = Color(0xFF485F84)
//internal val SurfaceDimDark = Color(0xFF121414)
//internal val SurfaceBrightDark = Color(0xFF37393A)
//internal val SurfaceContainerLowestDark = Color(0xFF0C0F0F)
//internal val SurfaceContainerLowDark = Color(0xFF1A1C1C)
//internal val SurfaceContainerDark = Color(0xFF1E2020)
//internal val SurfaceContainerHighDark = Color(0xFF282A2B)
//internal val SurfaceContainerHighestDark = Color(0xFF333535)
