package ru.hse.app.hasslspace.ui.theme

import androidx.compose.ui.graphics.Color

//generated by https://materialkolor.com
//Color palette was taken here: https://coolors.co/palette/e63946-f1faee-a8dadc-457b9d-1d3557

internal val Seed = Color(0xFF1D3557)

// Светлая тема
internal val BackgroundLight = Color(0xFFFFFFFF) // Белый
internal val SurfaceContainerLight = Color(0xFFEBEBEB) // Светло-серый
internal val SurfaceBrightLight = Color(0xFF013648)
internal val OnBackgroundLight = Color(0xFF000000) // Черный
internal val PrimaryLight = Color(0xFF013648) // Синий
internal val OnPrimaryLight = Color(0xFFFFFFFF) // Белый
internal val OnPrimaryContainerLight = Color(0xFFFFFFFF) // Белый
internal val SecondaryLight = Color(0xFFCFEDFF) // Голубой
internal val OnSecondaryLight = Color(0xFF000000) // Черный
internal val TertiaryLight = Color(0xFFF3D0B2) // Бежевый
internal val OnTertiaryLight = Color(0xFF000000) // Черный
internal val ErrorLight = Color(0xFFFF383C) // Ярко-красный
internal val OnErrorLight = Color(0xFFFFA4A4) // Бледно-красный
internal val SurfaceVariantLight = Color(0xFF2A9A47) // Ярко-зеленый
internal val OnSurfaceVariantLight = Color(0xFFB9FFA4) // Бледно-зеленый
internal val SurfaceLight = Color(0xFFD0D7DD) // Средне-серый
internal val OutlineLight = Color(0xFF6D6F6E) // Темно-серый
internal val OnSurfaceLight = Color(0xFF6D6F6E)
internal val ScrimLight = Color(0xFFFFFFFF) //Белый
internal val SurfaceDimLight = Color(0x00000000)

internal val SurfaceContainerLowLight = Color(0x0D000000)

// Темная тема

internal val BackgroundDark = Color(0xFF121212) // Почти черный фон
internal val SurfaceContainerDark = Color(0xFF186286) // Для карточек с друзьями
internal val SurfaceBrightDark = Color(0xFFB6ECFF)
internal val OnBackgroundDark = Color(0xFFFFFFFF) // Черный
internal val PrimaryDark = Color(0xFF4FA3BF) // Осветлённый синий из PrimaryLight
internal val OnPrimaryDark = Color(0xFF001F2A) // Очень тёмный сине-черный
internal val OnPrimaryContainerDark = Color(0xC6125F86) // Очень тёмный сине-черный

internal val SecondaryDark = Color(0xFF6FA4D6) // Более насыщенный голубой
internal val OnSecondaryDark = Color(0xFFFFFFFF)

internal val TertiaryDark = Color(0xC6C49366) // Тёплый бежевый, мягкий
internal val OnTertiaryDark = Color(0xFFFFFFFF)

internal val ErrorDark = Color(0xFFFF6B6E) // Мягче, чем ярко-красный
internal val OnErrorDark = Color(0xFF3A0002)

internal val SurfaceVariantDark = Color(0xFF3FBF63) // Зелёный остаётся живым
internal val OnSurfaceVariantDark = Color(0xFF0F2A16)

internal val SurfaceDark = Color(0xFF1E1E1E) // Карточки, bottom bar, поля
internal val OnSurfaceDark = Color(0xFFD5D5D5)
internal val OutlineDark = Color(0xFFA0A0A0) // Контуры, бордеры, divider
internal val ScrimDark = Color(0xFFFFFFFF) //Белый
internal val SurfaceDimDark = Color(0x00000000)
internal val SurfaceContainerLowDark = Color(0x26FFFFFF)
